stages:
  - release
release:
  stage: release
  image: node:12-alpine
  only:
    - master
  script:
    - echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}' > .npmrc
    - npm publish